<?php

	// This script runs only via command line
	//sleep(5);
	include(dirname(__FILE__)."/../../includes/config.inc.php");
	include(dirname(__FILE__)."/functions_system.php");
	
	$videoRootFolder=BASEDIR."/files/videos/";
	$originalRootFolder=BASEDIR."/files/original/";

	/**
	 * Prefix generated by the encoder job used to specify that the coresponding file is the original.
	 * The original files are stored in a dirrerent folder (files/original and not files/videos)
	 * @var string $prefixOriginal
	 */
	$prefixOriginal="original";
	
	global $db;
	// get all enconded videos file that have been connected to a video data 
	$query='SELECT * FROM '.table("job").' WHERE `status`="Encoded" AND `idvideo` IS NOT NULL AND `idvideo`<>0';
	$result=$db->_select($query);

	if (count($result)>0){
		foreach ($result as $res){
			$jobName=$res["name"];
			echo "job name : ".$jobName."\n";
			$jobExtension=$res["extension"];
			echo "job extension : ".$jobExtension."\n";
			// Create the full path of the file to be donwloaded
			$srcFullpath= $res["encodedsrc"].$jobName.'.'.$jobExtension;
			echo "src fullpath : ".$srcFullpath."\n";
				
			$query='SELECT * FROM '.table("video").' WHERE `videoid`='.$res["idvideo"];
			$vresult=$db->_select($query);
			echo "idvideo : ".$res["idvideo"]."\n";
				
			if (count($vresult>0)){
				$filename=$vresult[0]["file_name"];
				echo "filename : ".$filename."\n";
				$fileDirectory=$vresult[0]['file_directory'];
				echo "fileDirectory : ".$fileDirectory."\n";
				/**
				 * $jobName is formated like this : "prefix_uniquekey". The prefix may be a video format size (480,720,1080...) 
				 * or an audio extention (mp3) or the "original" string. The operation to compute in this script depends on this prefi :
				 * <ul>
				 * 		<li> If the prefix is equal to the extension stored into the job fields then we considere that the name 
				 * 			don't have to be changed and the output file pattern will be "FileName.extension" where FileName 
				 * 			come from the video table and the extension come from the job table. The file will be stored in 
				 * 			the /files/videos sunbolders.
				 * 		</li>
				 * 		<li> If the prefix is 'original" then the name will be unchanged like in the previous case 
				 * 			but it will be stored into the /files/original subfolders.
				 * 		</li>
				 * 		<li> If the extension corresponds to a video size then his size will be concatenated at the end
				 * 			of video name and the file will be stored into tih files/videos subfolders. (ie: videoXYZ-720.mp4)
				 * 		</li>
				 * </ul>
				 */
				$table=explode("_", $jobName);
				if ($table[0]==$prefixOriginal)
					$dstFullpath=dirname(__FILE__)."/../../files/original/".$fileDirectory."/".$filename;
				else {
					$dstFullpath=dirname(__FILE__)."/../../files/videos/".$fileDirectory."/".$filename;
					if ($table[0]!=$jobExtension)
						$dstFullpath.="-".$table[0];
				}
				$dstFullpath.=".".$jobExtension;
				echo "dstFullpath : ".$dstFullpath."\n";
				$process = new Process("wget \"$srcFullpath\" -O \"$dstFullpath\"");
				$query='UPDATE '.table("job").' SET `status` = "Completed" wHERE id="'.$res["id"].'"';
				echo $query."\n";
				$db->Execute($query);
			echo "\n";
			}
		}
	}
	else {
		echo "Pas de vidéo à transferer\n";
	}
	
